
#' MH-Algorithm for a Univariate Beta target distribution.
#' 
#' \code{} The BetaMH function returns the Markov chain generated by a random walk Metropolis-Hasting 
#' algorithm having a univariate beta distribution as target distribution.
#' @param x A number
#' @param y A number
#' @return The sum of \code{x} and \code{y}
#' @examples
#' add(1, 1)
#' add(10, 1)
BetaMH <- function(data, n, sigma, alpha_prior, beta_prior, s, x_0) {
  ans <- .C("BetaMH", as.double(data), as.integer(length(data)), as.integer(n), as.double(sigma), as.double(alpha_prior), as.double(beta_prior), as.integer(s), as.double(x_0), vec_xP=as.double(rep(0, n+1)))
  return(ans$vec_xP)
}

