#' MH-Algorithm for a Univariate Beta target distribution.
#' 
#' \code{} The BetaMH function returns the Markov chain generated by a random walk Metropolis-Hasting 
#' algorithm having a univariate beta distribution as target distribution.
#' @param data Observations distributed as an Binomial distribution.
#' @param n The required number of iterations for the MH-algorithm.
#' @param sigma The value of the standard deviation for the Gaussian proposal distribution of the random-walk MH-algorithm.
#' @param alpha_prior The prior value of the first non-negative parameter of the Beta prior distribution of the probability of success. 
#' @param beta_prior The prior value of second non-negative parameter of the Beta prior distribution of the probability of success.
#' @param s The number of machines on which to run the MH-algorithm. The value ranges between 1 and 4. Must be set different to 1 if running in parallel.
#' @param x_0 The initial value for the unknown parameter of the Beta target distribution.
#' 
#' @return The function returns a vector with the values of the Markov chain generated by the MH-algorithm.
#' @examples
#' # Generate data
#' observations = rbinom(10000, size = 1, prob = 0.5)
#' 
#' # Set the parameters for the function
#' nr_servers = 1 
#' n_iter = 1000
#' burn_in = 0.1*n_iter
#' sigma = 0.01
#' alpha_prior = 1.0
#' beta_prior = 1.0
#' x_0 = 0.1
#' 
#' 
#' # Run the function for the chosen parameters
#' markov_chain = NormalMH(observations,
#'                n_iter = n_iter,
#'                sigma = sigma, 
#'                alpha_prior = alpha_prior, 
#'                beta_prior = beta_prior, 
#'                s = 1, 
#'                x_0 = x_0)
#' 


BetaMH <- function(data, n, sigma, alpha_prior, beta_prior, s, x_0) {
  ans <- .C("BetaMH", as.double(data), as.integer(length(data)), as.integer(n), as.double(sigma), as.double(alpha_prior), as.double(beta_prior), as.integer(s), as.double(x_0), vec_xP=as.double(rep(0, n+1)))
  return(ans$vec_xP)
}

