
#' MH-Algorithm for a Univariate Gamma target distribution.
#' 
#' \code{} The GammaMH function returns the Markov chain generated by a random walk Metropolis-Hasting 
#' algorithm having a univariate gamma distribution as target distribution.
#' @param x A number
#' @param y A number
#' @return The sum of \code{x} and \code{y}
#' @examples
#' add(1, 1)
#' add(10, 1)
GammaMH <- function(data, n, sigma, k_prior, theta_prior, s, x_0) {
  ans <- .C("gammaMH", as.integer(data), as.integer(length(data)), as.integer(n), as.double(sigma), as.double(k_prior), as.double(theta_prior), as.integer(s), as.double(x_0), vec_xP=as.double(rep(0, n+1)))
  return(ans$vec_xP)
}

