#' MH-Algorithm for a multivariate Logistic regression.
#' 
#' \code{} The LogisticMH function returns the Markov chain generated by a random walk Metropolis-Hasting 
#' algorithm targeting the posterior distribution of the beta parameter in the logistic regression.
#' @param data_frame Dataframe containing the response variable y of the logistic regression and the explanatory variables Z.
#' @param n The required number of iterations for the MH-algorithm.
#' @param sigma The vector of standard deviations for the Gaussian proposal distribution (used in the MH-algorithm) for the beta parameters.  
#' @param sigma_prior The vector of prior standard deviations for the distribution of the unknown beta parameters.
#' @param mean_prior The vector of prior means for the distribution of the unknown beta parameters.
#' @param s The number of machines on which to run the MH-algorithm. The value ranges between 1 and 4. Must be set different to 1 if running in parallel.
#' @param x_0 The initial value for the unknown beta parameters.
#' 
#' @return The function returns a dataframe with the values of the Markov chain generated by the MH-algorithm.
#' @examples
#' # Load the data for the logistic regression
#' # not run
#' # data_frame = load('logistic_data_frame.RData') 
#' 
#' # Set the parameters for the function
#' n_iter = 10000
#' sigma = c(0.1, 0.1, 0.1, 0.1, 0.1)   
#' sigma_prior = c(1,1,1,1,1)           
#' mean_prior = c(-2, 0.5, 0, 0.5, 2)    
#' nr_servers = 1      
#' x_0 = c(-3.5,1.7,-0.2,0.5,3.5)  
#'            
#' # Run the function for the chosen parameters
#' markov_chain = LogisticMH(data_frame = data_frame ,
#'                           n_iter = n_iter, 
#'                           sigma = sigma, 
#'                           sigma_prior = sigma_prior, 
#'                           mean_prior = mean_prior, 
#'                           s = nr_servers, 
#'                           x_0 = x_0)

#' 

LogisticMH <- function(data_frame,  n_iter, sigma, sigma_prior, mean_prior, s, x_0) {
  data <- data_frame$y
  z <- as.matrix(subset(data_frame, select =  -c(y)))
  ans <- .C("LogisticMH", as.integer(data), as.vector(as.double(t(z))), as.integer(length(data)), 
            as.integer(ncol(z)), as.integer(n_iter), as.double(sigma), as.double(sigma_prior), 
            as.double(mean_prior), as.integer(s), as.double(x_0),  vec_xP=as.double(rep(0, (n_iter+1)*(ncol(z)))))
  
  result <- as.data.frame(matrix(ans$vec_xP, ncol = ncol(z), byrow=TRUE))
  colnames(result) <- paste0('beta_', seq_len(ncol(z))-1)
  return(result)
}

