
#' MH-Algorithm for a Univariate Normal target distribution.
#' 
#' \code{} The NormalMH function returns the Markov chain generated by a random walk Metropolis-Hasting 
#' algorithm having a univariate normal distribution as target distribution.
#' @param data Observations distributed as an univariate normal distribution with unknown mean and known variance.
#' @param n The required number of iterations for the MH-algorithm.
#' @param sigma The value of the satandard deviation for the Gaussian proposal distribution of the random-walk MH-algorithm.
#' @param mean_prior The prior mean value for the unknown parameter. 
#' @param sigma_prior The prior standard deviation value for the unknown parameter.
#' @param sigma_known The value of the known parameter.
#' @param s The number of machines on which to run the MH-algorithm.
#' @param x_0 The initial value for the unknown parameter.
#' 
#' @return The function returns a vector with the values of the Markov chain generated by the MH-algorithm.
#' @examples
#' add(1, 1)
#' add(10, 1)


NormalMH <- function(data, n, sigma, mean_prior, sigma_prior, sigma_known, s, x_0) {
  ans <- .C("normalMH", as.double(data), as.integer(length(data)), as.integer(n), as.double(sigma), as.double(mean_prior), as.double(sigma_prior), as.double(sigma_known) , as.integer(s), as.double(x_0), vec_xP=as.double(rep(0, n+1)))
  return(ans$vec_xP)
}

