#' MH-Algorithm for a Univariate Normal target distribution run using multiple cores.
#' 
#' \code{} The NormalMultiCoreMH function returns the Markov chain generated by a random walk Metropolis-Hasting 
#' algorithm having a univariate normal distribution as target distribution. It also allows the user to run the algorithm on multiple cores.
#' @param multicore Integer value equal to 1 or 0.  If 1, the algorithms uses multiple cores. 
#' @param data Observations distributed as an univariate normal distribution with unknown mean and known variance.
#' @param n The required number of iterations for the MH-algorithm.
#' @param sigma The value of the standard deviation for the Gaussian proposal distribution of the random-walk MH-algorithm.
#' @param mean_prior The prior mean value for the unknown parameter. 
#' @param sigma_prior The prior standard deviation value for the unknown parameter.
#' @param sigma_known The value of the known parameter.
#' @param s The number of machines (not the cores) on which to run the MH-algorithm. The value ranges between 1 and 4. Must be set different to 1 if running in parallel.
#' @param x_0 The initial value for the unknown parameter.
#' @param num_cores The number of cores the algorithm uses if multicore == 1.
#' 
#' @return The function returns a vector with the values of the Markov chain generated by the MH-algorithm.
#' @examples
#' # Generate data
#' observations = rnorm(10000, 1 , sigma_known)
#' 
#' # Set the parameters for the function
#' multicore = 1
#' n_iter = 1000
#' sigma = 0.01
#' mean_prior = 0.0
#' sigma_prior = 1.0
#' sigma_known = 1
#' nr_servers = 1 
#' x_0 = 0.0
#' num_cores = 4
#' 
#' # Run the function for the chosen parameters
#' markov_chain = NormalMH(multicore = multicore, 
#'                observations = observations, 
#'                n = n_iter, 
#'                sigma = sigma, 
#'                mean_prior = mean_prior, 
#'                sigma_prior = sigma_prior, 
#'                sigma_known = sigma_known, 
#'                s = nr_servers, 
#'                x_0 = x_0, 
#'                num_cores = num_cores) 
#' 
#' 
NormalMultiCoreMH <- function(multicore, data, n, sigma, mean_prior, sigma_prior, sigma_known, s, x_0, num_cores) {
  ans <- .C("NormalMultiCoreMH", as.integer(multicore), as.double(data), as.integer(length(data)), as.integer(n), as.double(sigma), as.double(mean_prior), as.double(sigma_prior), as.double(sigma_known) , as.integer(s), as.double(x_0), as.integer(num_cores), vec_xP=as.double(rep(0, n+1)))
  return(ans$vec_xP)
}

