
#' MH-Algorithm for a Univariate Normal target distribution.
#' 
#' \code{} The NormalMH function returns the Markov chain generated by a random walk Metropolis-Hasting 
#' algorithm having a univariate normal distribution as target distribution.
#' @param data Observations distributed as an univariate normal distribution with unknown mean and known variance.
#' @param n The required number of iterations for the MH-algorithm.
#' @param sigma The value of the satandard deviation for the Gaussian proposal distribution of the random-walk MH-algorithm.
#' @param mean_prior The prior mean value for the unknown parameter. 
#' @param sigma_prior The prior standard deviation value for the unknown parameter.
#' @param sigma_known The value of the known parameter.
#' @param s The number of machines on which to run the MH-algorithm. The value ranges between 1 and 4. Must be set different to 1 if running in parallel.
#' @param x_0 The initial value for the unknown parameter.
#' 
#' @return The function returns a vector with the values of the Markov chain generated by the MH-algorithm.
#' @examples
#' # Generate data
#' observations <- rnorm(10000, 1 , sigma_known)
#' 
#' # Set the parameters for the function
#' sigma_known = 1
#' nr_servers = 1 
#' n_iter = 1000
#' burn_in = 0.1*n_iter
#' sigma = 0.01
#' mean_prior = 0.0
#' sigma_prior = 1.0
#' x_0 = 0.0
#' 
#' # Run the function for the chosen parameters
#' markov_chain = NormalMH(observations, 
#'                n = n_iter, 
#'                sigma = sigma, 
#'                mean_prior = mean_prior, 
#'                sigma_prior = sigma_prior, 
#'                sigma_known = sigma_known, 
#'                s = nr_servers, 
#'                x_0 = x_0) 
#' 
#' 


NormalMH <- function(data, n, sigma, mean_prior, sigma_prior, sigma_known, s, x_0) {
  ans <- .C("normalMH", as.double(data), as.integer(length(data)), as.integer(n), as.double(sigma), as.double(mean_prior), as.double(sigma_prior), as.double(sigma_known) , as.integer(s), as.double(x_0), vec_xP=as.double(rep(0, n+1)))
  return(ans$vec_xP)
}

