
#' MH-Algorithm for a Univariate Normal target distribution.
#' 
#' \code{} The NormalMH function returns the Markov chain generated by a random walk Metropolis-Hasting 
#' algorithm having a univariate normal distribution as target distribution.
#' @param x A number
#' @param y A number
#' @return The sum of \code{x} and \code{y}
#' @examples
#' add(1, 1)
#' add(10, 1)


NormalMH <- function(data, n, sigma, mean_prior, sigma_prior, sigma_known, s, x_0) {
  ans <- .C("normalMH", as.double(data), as.integer(length(data)), as.integer(n), as.double(sigma), as.double(mean_prior), as.double(sigma_prior), as.double(sigma_known) , as.integer(s), as.double(x_0), vec_xP=as.double(rep(0, n+1)))
  return(ans$vec_xP)
}

